//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.09 at 02:38:11 PM EET 
//


package edu.pragmatic.example.students;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.pragmatic.example.students package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.pragmatic.example.students
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HighSchool }
     * 
     */
    public HighSchool createHighSchool() {
        return new HighSchool();
    }

    /**
     * Create an instance of {@link HighSchool.People }
     * 
     */
    public HighSchool.People createHighSchoolPeople() {
        return new HighSchool.People();
    }

    /**
     * Create an instance of {@link HighSchool.People.Students }
     * 
     */
    public HighSchool.People.Students createHighSchoolPeopleStudents() {
        return new HighSchool.People.Students();
    }

    /**
     * Create an instance of {@link HighSchool.People.Students.Student }
     * 
     */
    public HighSchool.People.Students.Student createHighSchoolPeopleStudentsStudent() {
        return new HighSchool.People.Students.Student();
    }

    /**
     * Create an instance of {@link HighSchool.People.Teachers }
     * 
     */
    public HighSchool.People.Teachers createHighSchoolPeopleTeachers() {
        return new HighSchool.People.Teachers();
    }

    /**
     * Create an instance of {@link HighSchool.Exams }
     * 
     */
    public HighSchool.Exams createHighSchoolExams() {
        return new HighSchool.Exams();
    }

    /**
     * Create an instance of {@link HighSchool.People.Students.Student.Exam }
     * 
     */
    public HighSchool.People.Students.Student.Exam createHighSchoolPeopleStudentsStudentExam() {
        return new HighSchool.People.Students.Student.Exam();
    }

    /**
     * Create an instance of {@link HighSchool.People.Teachers.Teacher }
     * 
     */
    public HighSchool.People.Teachers.Teacher createHighSchoolPeopleTeachersTeacher() {
        return new HighSchool.People.Teachers.Teacher();
    }

    /**
     * Create an instance of {@link HighSchool.Exams.Exam }
     * 
     */
    public HighSchool.Exams.Exam createHighSchoolExamsExam() {
        return new HighSchool.Exams.Exam();
    }

}
